version: '2'
services:
  redis:
    image: redis
    volumes:
      - ./tmp/docker/redis/data:/data
  app:
    image: clojure
    volumes:
      - ./app:/code
    working_dir: /code
    command: lein run
    env_file:
      - .env
    depends_on:
      - redis
    # ports:
    #   - "4000:4000"
